#ifndef ANAR_PARSPARK_CONFIG_HPP
#define ANAR_PARSPARK_CONFIG_HPP

#define PROJECT_NAME "ParsPark"
#define PROJECT_VER "0.0.0"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "0"
#define PROJECT_VER_PATCH "0"

#endif  // ANAR_PARSPARK_CONFIG_HPP
