/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `lost_card`;

CREATE TABLE `lost_card` (
  `creating_user_id` BIGINT UNSIGNED NOT NULL,
  `updating_user_id` BIGINT UNSIGNED NULL,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_time` timestamp NULL , 
CHECK(`updated_time` > `created_time`),
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `card_id` BIGINT UNSIGNED NOT NULL,
  `car_id` BIGINT UNSIGNED NOT NULL,
  `penalty_cost` INT UNSIGNED NOT NULL CHECK(`penalty_cost` > 999),
  `description` VARCHAR(4096) NOT NULL CHECK(`description` != ''))
 ENGINE=InnoDB;


ALTER TABLE `lost_card`
  ADD CONSTRAINT `lost_card_creating_user_id_fk`
    FOREIGN KEY (`creating_user_id`)
    REFERENCES `user` (`id`),
  ADD CONSTRAINT `lost_card_updating_user_id_fk`
    FOREIGN KEY (`updating_user_id`)
    REFERENCES `user` (`id`),
  ADD CONSTRAINT `lost_card_card_id_fk`
    FOREIGN KEY (`card_id`)
    REFERENCES `card` (`id`),
  ADD CONSTRAINT `lost_card_car_id_fk`
    FOREIGN KEY (`car_id`)
    REFERENCES `car` (`id`)


