/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `person`;

CREATE TABLE `person` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL CHECK(`first_name` != ''),
  `last_name` VARCHAR(100) NOT NULL CHECK(`last_name` != ''),
  `national_card_number` BIGINT UNSIGNED NULL CHECK(`national_card_number` BETWEEN 1000000000 AND 9999999999),
  `age` TINYINT UNSIGNED NULL CHECK(`age` BETWEEN 1 AND 127),
  `person_contact_id` BIGINT UNSIGNED NULL,
  `business_contact_id` BIGINT UNSIGNED NULL,
  `picture_address` VARCHAR(1024) NULL CHECK(`picture_address` != ''))
 ENGINE=InnoDB;

/*
ALTER TABLE `person`
  ADD CONSTRAINT `person_person_contact_id_fk`
    FOREIGN KEY (`person_contact_id`)
    REFERENCES `contact` (`id`),
  ADD CONSTRAINT `person_business_contact_id_fk`
    FOREIGN KEY (`business_contact_id`)
    REFERENCES `contact` (`id`)
*/

