/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `contact`;

CREATE TABLE `contact` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL CHECK(`email` != ''),
  `address` VARCHAR(500) NULL CHECK(`address` != ''),
  `phone` VARCHAR(12) NULL CHECK(`phone` != ''),
  `mobile` VARCHAR(12) NULL CHECK(`mobile` != ''))
 ENGINE=InnoDB;

