/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `driver`;

CREATE TABLE `driver` (
  `creating_user_id` BIGINT UNSIGNED NOT NULL,
  `updating_user_id` BIGINT UNSIGNED NULL,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_time` timestamp NULL , 
CHECK(`updated_time` > `created_time`),
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `driving_license_number` VARCHAR(100) NULL CHECK(`driving_license_number` != ''),
  `person_id` BIGINT UNSIGNED NOT NULL,
  `organization_id` BIGINT UNSIGNED NULL,
  `picture_address` VARCHAR(1024) NULL CHECK(`picture_address` != ''))
 ENGINE=InnoDB;

/*
ALTER TABLE `driver`
  ADD CONSTRAINT `driver_creating_user_id_fk`
    FOREIGN KEY (`creating_user_id`)
    REFERENCES `user` (`id`),
  ADD CONSTRAINT `driver_updating_user_id_fk`
    FOREIGN KEY (`updating_user_id`)
    REFERENCES `user` (`id`),
  ADD CONSTRAINT `driver_person_id_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `person` (`id`),
  ADD CONSTRAINT `driver_organization_id_fk`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organization` (`id`)
*/

