// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef LOST_CARD_MODEL_ODB_HXX
#define LOST_CARD_MODEL_ODB_HXX

// Begin prologue.
//
#include "service/model-binding/database/traits/traits.hxx"
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "lost-card-model.hpp"

#include "car-model-odb.hxx"
#include "card-model-odb.hxx"
#include "create-modify-delete-model-odb.hxx"
#include "driver-model-odb.hxx"
#include "organization-model-odb.hxx"
#include "person-model-odb.hxx"
#include "user-model-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // LostCardModel
  //
  template <>
  struct class_traits< ::anar::parspark::model::LostCardModel >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::anar::parspark::model::LostCardModel >
  {
    public:
    typedef ::anar::parspark::model::LostCardModel object_type;
    typedef ::std::shared_ptr< ::anar::parspark::model::LostCardModel > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint64_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // LostCardModel
  //
  template <typename A>
  struct pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >:
    pointer_query_columns< ::anar::parspark::model::CreateModifyDeleteModel, id_mysql, A >
  {
    // CreateModifyDeleteModel
    //
    typedef pointer_query_columns< ::anar::parspark::model::CreateModifyDeleteModel, id_mysql, A > CreateModifyDeleteModel;

    // Id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint64_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    Id_type_;

    static const Id_type_ Id;

    // Card
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint64_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    Card_type_;

    static const Card_type_ Card;

    // Car
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint64_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    Car_type_;

    static const Car_type_ Car;

    // PenaltyCost
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint32_t,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    PenaltyCost_type_;

    static const PenaltyCost_type_ PenaltyCost;

    // Description
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Description_type_;

    static const Description_type_ Description;
  };

  template <typename A>
  const typename pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::Id_type_
  pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  Id (A::table_name, "`id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::Card_type_
  pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  Card (A::table_name, "`card_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::Car_type_
  pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  Car (A::table_name, "`car_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::PenaltyCost_type_
  pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  PenaltyCost (A::table_name, "`penalty_cost`", 0);

  template <typename A>
  const typename pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::Description_type_
  pointer_query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  Description (A::table_name, "`description`", 0);

  template <>
  class access::object_traits_impl< ::anar::parspark::model::LostCardModel, id_mysql >:
    public access::object_traits< ::anar::parspark::model::LostCardModel >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type: object_traits_impl< ::anar::parspark::model::CreateModifyDeleteModel, id_mysql >::image_type
    {
      // Id
      //
      unsigned long long Id_value;
      my_bool Id_null;

      // Card
      //
      unsigned long long Card_value;
      my_bool Card_null;

      // Car
      //
      unsigned long long Car_value;
      my_bool Car_null;

      // PenaltyCost
      //
      unsigned int PenaltyCost_value;
      my_bool PenaltyCost_null;

      // Description
      //
      details::buffer Description_value;
      unsigned long Description_size;
      my_bool Description_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct Card_tag;
    struct Car_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::anar::parspark::model::LostCardModel, id_common >:
    public access::object_traits_impl< ::anar::parspark::model::LostCardModel, id_mysql >
  {
  };

  // LostCardModel
  //
  template <>
  struct alias_traits<
    ::anar::parspark::model::CardModel,
    id_mysql,
    access::object_traits_impl< ::anar::parspark::model::LostCardModel, id_mysql >::Card_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::anar::parspark::model::CarModel,
    id_mysql,
    access::object_traits_impl< ::anar::parspark::model::LostCardModel, id_mysql >::Car_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::anar::parspark::model::LostCardModel, id_mysql >
  {
    // Card
    //
    typedef
    odb::alias_traits<
      ::anar::parspark::model::CardModel,
      id_mysql,
      access::object_traits_impl< ::anar::parspark::model::LostCardModel, id_mysql >::Card_tag>
    Card_alias_;

    // Car
    //
    typedef
    odb::alias_traits<
      ::anar::parspark::model::CarModel,
      id_mysql,
      access::object_traits_impl< ::anar::parspark::model::LostCardModel, id_mysql >::Car_tag>
    Car_alias_;
  };

  template <typename A>
  struct query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >:
    query_columns_base< ::anar::parspark::model::LostCardModel, id_mysql >,
    query_columns< ::anar::parspark::model::CreateModifyDeleteModel, id_mysql, A >
  {
    // CreateModifyDeleteModel
    //
    typedef query_columns< ::anar::parspark::model::CreateModifyDeleteModel, id_mysql, A > CreateModifyDeleteModel;

    // Id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint64_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    Id_type_;

    static const Id_type_ Id;

    // Card
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint64_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    Card_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::anar::parspark::model::CardModel,
        id_mysql,
        Card_alias_ > >
    Card_pointer_type_;

    struct Card_type_: Card_pointer_type_, Card_column_type_
    {
      Card_type_ (const char* t, const char* c, const char* conv)
        : Card_column_type_ (t, c, conv)
      {
      }
    };

    static const Card_type_ Card;

    // Car
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint64_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    Car_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::anar::parspark::model::CarModel,
        id_mysql,
        Car_alias_ > >
    Car_pointer_type_;

    struct Car_type_: Car_pointer_type_, Car_column_type_
    {
      Car_type_ (const char* t, const char* c, const char* conv)
        : Car_column_type_ (t, c, conv)
      {
      }
    };

    static const Car_type_ Car;

    // PenaltyCost
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint32_t,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    PenaltyCost_type_;

    static const PenaltyCost_type_ PenaltyCost;

    // Description
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Description_type_;

    static const Description_type_ Description;
  };

  template <typename A>
  const typename query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::Id_type_
  query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  Id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::Card_type_
  query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  Card (A::table_name, "`card_id`", 0);

  template <typename A>
  const typename query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::Car_type_
  query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  Car (A::table_name, "`car_id`", 0);

  template <typename A>
  const typename query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::PenaltyCost_type_
  query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  PenaltyCost (A::table_name, "`penalty_cost`", 0);

  template <typename A>
  const typename query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::Description_type_
  query_columns< ::anar::parspark::model::LostCardModel, id_mysql, A >::
  Description (A::table_name, "`description`", 0);
}

#include "lost-card-model-odb.ixx"

#include <odb/post.hxx>

#endif // LOST_CARD_MODEL_ODB_HXX
