// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ORGANIZATION_MODEL_ODB_HXX
#define ORGANIZATION_MODEL_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <cstddef>
#include <memory>
#include <odb/callback.hxx>
#include <odb/container-traits.hxx>
#include <odb/core.hxx>
#include <odb/details/shared-ptr.hxx>
#include <odb/details/unused.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/pre.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>
#include <odb/traits.hxx>
#include <odb/wrapper-traits.hxx>
#include <utility>

#include "contact-model-odb.hxx"
#include "create-modify-delete-model-odb.hxx"
#include "model/organization-model.hpp"
#include "person-model-odb.hxx"
#include "user-model-odb.hxx"

namespace odb
{
  // OrganizationModel
  //
  template <>
  struct class_traits< ::anar::model::OrganizationModel >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::anar::model::OrganizationModel >
  {
    public:
    typedef ::anar::model::OrganizationModel object_type;
    typedef ::std::shared_ptr< ::anar::model::OrganizationModel > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint64_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // OrganizationModel
  //
  template <typename A>
  struct pointer_query_columns< ::anar::model::OrganizationModel, id_mysql, A >:
    pointer_query_columns< ::anar::model::CreateModifyDeleteModel, id_mysql, A >
  {
    // CreateModifyDeleteModel
    //
    typedef pointer_query_columns< ::anar::model::CreateModifyDeleteModel, id_mysql, A > CreateModifyDeleteModel;

    // Id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint64_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    Id_type_;

    static const Id_type_ Id;

    // Name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Name_type_;

    static const Name_type_ Name;

    // Abbreviation
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Abbreviation_type_;

    static const Abbreviation_type_ Abbreviation;

    // PictureAddress
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    PictureAddress_type_;

    static const PictureAddress_type_ PictureAddress;
  };

  template <typename A>
  const typename pointer_query_columns< ::anar::model::OrganizationModel, id_mysql, A >::Id_type_
  pointer_query_columns< ::anar::model::OrganizationModel, id_mysql, A >::
  Id (A::table_name, "`id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::anar::model::OrganizationModel, id_mysql, A >::Name_type_
  pointer_query_columns< ::anar::model::OrganizationModel, id_mysql, A >::
  Name (A::table_name, "`name`", 0);

  template <typename A>
  const typename pointer_query_columns< ::anar::model::OrganizationModel, id_mysql, A >::Abbreviation_type_
  pointer_query_columns< ::anar::model::OrganizationModel, id_mysql, A >::
  Abbreviation (A::table_name, "`abbreviation`", 0);

  template <typename A>
  const typename pointer_query_columns< ::anar::model::OrganizationModel, id_mysql, A >::PictureAddress_type_
  pointer_query_columns< ::anar::model::OrganizationModel, id_mysql, A >::
  PictureAddress (A::table_name, "`picture_address`", 0);

  template <>
  class access::object_traits_impl< ::anar::model::OrganizationModel, id_mysql >:
    public access::object_traits< ::anar::model::OrganizationModel >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type: object_traits_impl< ::anar::model::CreateModifyDeleteModel, id_mysql >::image_type
    {
      // Id
      //
      unsigned long long Id_value;
      my_bool Id_null;

      // Name
      //
      details::buffer Name_value;
      unsigned long Name_size;
      my_bool Name_null;

      // Abbreviation
      //
      details::buffer Abbreviation_value;
      unsigned long Abbreviation_size;
      my_bool Abbreviation_null;

      // PictureAddress
      //
      details::buffer PictureAddress_value;
      unsigned long PictureAddress_size;
      my_bool PictureAddress_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::anar::model::OrganizationModel, id_common >:
    public access::object_traits_impl< ::anar::model::OrganizationModel, id_mysql >
  {
  };

  // OrganizationModel
  //
  template <typename A>
  struct query_columns< ::anar::model::OrganizationModel, id_mysql, A >:
    query_columns< ::anar::model::CreateModifyDeleteModel, id_mysql, A >
  {
    // CreateModifyDeleteModel
    //
    typedef query_columns< ::anar::model::CreateModifyDeleteModel, id_mysql, A > CreateModifyDeleteModel;

    // Id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::uint64_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    Id_type_;

    static const Id_type_ Id;

    // Name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Name_type_;

    static const Name_type_ Name;

    // Abbreviation
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Abbreviation_type_;

    static const Abbreviation_type_ Abbreviation;

    // PictureAddress
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    PictureAddress_type_;

    static const PictureAddress_type_ PictureAddress;
  };

  template <typename A>
  const typename query_columns< ::anar::model::OrganizationModel, id_mysql, A >::Id_type_
  query_columns< ::anar::model::OrganizationModel, id_mysql, A >::
  Id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::anar::model::OrganizationModel, id_mysql, A >::Name_type_
  query_columns< ::anar::model::OrganizationModel, id_mysql, A >::
  Name (A::table_name, "`name`", 0);

  template <typename A>
  const typename query_columns< ::anar::model::OrganizationModel, id_mysql, A >::Abbreviation_type_
  query_columns< ::anar::model::OrganizationModel, id_mysql, A >::
  Abbreviation (A::table_name, "`abbreviation`", 0);

  template <typename A>
  const typename query_columns< ::anar::model::OrganizationModel, id_mysql, A >::PictureAddress_type_
  query_columns< ::anar::model::OrganizationModel, id_mysql, A >::
  PictureAddress (A::table_name, "`picture_address`", 0);
}

#include "organization-model-odb.ixx"

#include <odb/post.hxx>

#endif // ORGANIZATION_MODEL_ODB_HXX
