/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `parking_log`;

CREATE TABLE `parking_log` (
  `creating_user_id` BIGINT UNSIGNED NOT NULL,
  `updating_user_id` BIGINT UNSIGNED NULL,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_time` timestamp NULL , 
CHECK(`updated_time` > `created_time`),
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `card_id` BIGINT UNSIGNED NOT NULL,
  `enter_plate_number` VARCHAR(50) NULL CHECK(`enter_plate_number` != ''),
  `exit_plate_number` VARCHAR(50) NULL CHECK(`exit_plate_number` != ''),
  `entered_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `exited_time` timestamp NULL ,
CHECK(`exited_time` > `entered_time`),
  `parking_cost` INT UNSIGNED NULL,
  `enter_picture_address` VARCHAR(1024) NULL CHECK(`enter_picture_address` != ''),
  `exit_picture_address` VARCHAR(1024) NULL CHECK(`exit_picture_address` != ''),
  `subscription_id` BIGINT UNSIGNED NULL)
 ENGINE=InnoDB;


ALTER TABLE `parking_log`
  ADD CONSTRAINT `parking_log_creating_user_id_fk`
    FOREIGN KEY (`creating_user_id`)
    REFERENCES `user` (`id`),
  ADD CONSTRAINT `parking_log_updating_user_id_fk`
    FOREIGN KEY (`updating_user_id`)
    REFERENCES `user` (`id`),
  ADD CONSTRAINT `parking_log_card_id_fk`
    FOREIGN KEY (`card_id`)
    REFERENCES `card` (`id`),
  ADD CONSTRAINT `parking_log_subscription_id_fk`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `subscription` (`id`)


