// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "person-model-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // PersonModel
  //

  struct access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::id_type
  access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::uint64_t,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::id_type
  access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::uint64_t,
          mysql::id_ulonglong >::set_value (
        id,
        i.Id_value,
        i.Id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // Id
    //
    t[0UL] = 0;

    // FirstName
    //
    if (t[1UL])
    {
      i.FirstName_value.capacity (i.FirstName_size);
      grew = true;
    }

    // LastName
    //
    if (t[2UL])
    {
      i.LastName_value.capacity (i.LastName_size);
      grew = true;
    }

    // NationalCardNumber
    //
    t[3UL] = 0;

    // Age
    //
    t[4UL] = 0;

    // Email
    //
    if (t[5UL])
    {
      i.Email_value.capacity (i.Email_size);
      grew = true;
    }

    // Address
    //
    if (t[6UL])
    {
      i.Address_value.capacity (i.Address_size);
      grew = true;
    }

    // Phone
    //
    if (t[7UL])
    {
      i.Phone_value.capacity (i.Phone_size);
      grew = true;
    }

    // Mobile
    //
    if (t[8UL])
    {
      i.Mobile_value.capacity (i.Mobile_size);
      grew = true;
    }

    // PictureAddress
    //
    if (t[9UL])
    {
      i.PictureAddress_value.capacity (i.PictureAddress_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // Id
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.Id_value;
      b[n].is_null = &i.Id_null;
      n++;
    }

    // FirstName
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.FirstName_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.FirstName_value.capacity ());
    b[n].length = &i.FirstName_size;
    b[n].is_null = &i.FirstName_null;
    n++;

    // LastName
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.LastName_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.LastName_value.capacity ());
    b[n].length = &i.LastName_size;
    b[n].is_null = &i.LastName_null;
    n++;

    // NationalCardNumber
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.NationalCardNumber_value;
    b[n].is_null = &i.NationalCardNumber_null;
    n++;

    // Age
    //
    b[n].buffer_type = MYSQL_TYPE_TINY;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.Age_value;
    b[n].is_null = &i.Age_null;
    n++;

    // Email
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.Email_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.Email_value.capacity ());
    b[n].length = &i.Email_size;
    b[n].is_null = &i.Email_null;
    n++;

    // Address
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.Address_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.Address_value.capacity ());
    b[n].length = &i.Address_size;
    b[n].is_null = &i.Address_null;
    n++;

    // Phone
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.Phone_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.Phone_value.capacity ());
    b[n].length = &i.Phone_size;
    b[n].is_null = &i.Phone_null;
    n++;

    // Mobile
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.Mobile_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.Mobile_value.capacity ());
    b[n].length = &i.Mobile_size;
    b[n].is_null = &i.Mobile_null;
    n++;

    // PictureAddress
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.PictureAddress_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.PictureAddress_value.capacity ());
    b[n].length = &i.PictureAddress_size;
    b[n].is_null = &i.PictureAddress_null;
    n++;
  }

  void access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // Id
    //
    if (sk == statement_insert)
    {
      ::uint64_t const& v =
        o.Id;

      bool is_null (false);
      mysql::value_traits<
          ::uint64_t,
          mysql::id_ulonglong >::set_image (
        i.Id_value, is_null, v);
      i.Id_null = is_null;
    }

    // FirstName
    //
    {
      ::std::string const& v =
        o.FirstName;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.FirstName_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.FirstName_value,
        size,
        is_null,
        v);
      i.FirstName_null = is_null;
      i.FirstName_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.FirstName_value.capacity ());
    }

    // LastName
    //
    {
      ::std::string const& v =
        o.LastName;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.LastName_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.LastName_value,
        size,
        is_null,
        v);
      i.LastName_null = is_null;
      i.LastName_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.LastName_value.capacity ());
    }

    // NationalCardNumber
    //
    {
      ::std::shared_ptr< long unsigned int > const& v =
        o.NationalCardNumber;

      bool is_null (true);
      mysql::value_traits<
          ::std::shared_ptr< long unsigned int >,
          mysql::id_ulonglong >::set_image (
        i.NationalCardNumber_value, is_null, v);
      i.NationalCardNumber_null = is_null;
    }

    // Age
    //
    {
      ::std::shared_ptr< unsigned char > const& v =
        o.Age;

      bool is_null (true);
      mysql::value_traits<
          ::std::shared_ptr< unsigned char >,
          mysql::id_utiny >::set_image (
        i.Age_value, is_null, v);
      i.Age_null = is_null;
    }

    // Email
    //
    {
      ::std::string const& v =
        o.Email;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.Email_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.Email_value,
        size,
        is_null,
        v);
      i.Email_null = is_null;
      i.Email_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.Email_value.capacity ());
    }

    // Address
    //
    {
      ::std::shared_ptr< ::std::basic_string< char > > const& v =
        o.Address;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.Address_value.capacity ());
      mysql::value_traits<
          ::std::shared_ptr< ::std::basic_string< char > >,
          mysql::id_string >::set_image (
        i.Address_value,
        size,
        is_null,
        v);
      i.Address_null = is_null;
      i.Address_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.Address_value.capacity ());
    }

    // Phone
    //
    {
      ::std::shared_ptr< ::std::basic_string< char > > const& v =
        o.Phone;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.Phone_value.capacity ());
      mysql::value_traits<
          ::std::shared_ptr< ::std::basic_string< char > >,
          mysql::id_string >::set_image (
        i.Phone_value,
        size,
        is_null,
        v);
      i.Phone_null = is_null;
      i.Phone_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.Phone_value.capacity ());
    }

    // Mobile
    //
    {
      ::std::shared_ptr< ::std::basic_string< char > > const& v =
        o.Mobile;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.Mobile_value.capacity ());
      mysql::value_traits<
          ::std::shared_ptr< ::std::basic_string< char > >,
          mysql::id_string >::set_image (
        i.Mobile_value,
        size,
        is_null,
        v);
      i.Mobile_null = is_null;
      i.Mobile_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.Mobile_value.capacity ());
    }

    // PictureAddress
    //
    {
      ::std::shared_ptr< ::std::basic_string< char > > const& v =
        o.PictureAddress;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.PictureAddress_value.capacity ());
      mysql::value_traits<
          ::std::shared_ptr< ::std::basic_string< char > >,
          mysql::id_string >::set_image (
        i.PictureAddress_value,
        size,
        is_null,
        v);
      i.PictureAddress_null = is_null;
      i.PictureAddress_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.PictureAddress_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // Id
    //
    {
      ::uint64_t& v =
        o.Id;

      mysql::value_traits<
          ::uint64_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.Id_value,
        i.Id_null);
    }

    // FirstName
    //
    {
      ::std::string& v =
        o.FirstName;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.FirstName_value,
        i.FirstName_size,
        i.FirstName_null);
    }

    // LastName
    //
    {
      ::std::string& v =
        o.LastName;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.LastName_value,
        i.LastName_size,
        i.LastName_null);
    }

    // NationalCardNumber
    //
    {
      ::std::shared_ptr< long unsigned int >& v =
        o.NationalCardNumber;

      mysql::value_traits<
          ::std::shared_ptr< long unsigned int >,
          mysql::id_ulonglong >::set_value (
        v,
        i.NationalCardNumber_value,
        i.NationalCardNumber_null);
    }

    // Age
    //
    {
      ::std::shared_ptr< unsigned char >& v =
        o.Age;

      mysql::value_traits<
          ::std::shared_ptr< unsigned char >,
          mysql::id_utiny >::set_value (
        v,
        i.Age_value,
        i.Age_null);
    }

    // Email
    //
    {
      ::std::string& v =
        o.Email;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.Email_value,
        i.Email_size,
        i.Email_null);
    }

    // Address
    //
    {
      ::std::shared_ptr< ::std::basic_string< char > >& v =
        o.Address;

      mysql::value_traits<
          ::std::shared_ptr< ::std::basic_string< char > >,
          mysql::id_string >::set_value (
        v,
        i.Address_value,
        i.Address_size,
        i.Address_null);
    }

    // Phone
    //
    {
      ::std::shared_ptr< ::std::basic_string< char > >& v =
        o.Phone;

      mysql::value_traits<
          ::std::shared_ptr< ::std::basic_string< char > >,
          mysql::id_string >::set_value (
        v,
        i.Phone_value,
        i.Phone_size,
        i.Phone_null);
    }

    // Mobile
    //
    {
      ::std::shared_ptr< ::std::basic_string< char > >& v =
        o.Mobile;

      mysql::value_traits<
          ::std::shared_ptr< ::std::basic_string< char > >,
          mysql::id_string >::set_value (
        v,
        i.Mobile_value,
        i.Mobile_size,
        i.Mobile_null);
    }

    // PictureAddress
    //
    {
      ::std::shared_ptr< ::std::basic_string< char > >& v =
        o.PictureAddress;

      mysql::value_traits<
          ::std::shared_ptr< ::std::basic_string< char > >,
          mysql::id_string >::set_value (
        v,
        i.PictureAddress_value,
        i.PictureAddress_size,
        i.PictureAddress_null);
    }
  }

  void access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          ::uint64_t,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::persist_statement[] =
  "INSERT INTO `person` "
  "(`id`, "
  "`first_name`, "
  "`last_name`, "
  "`national_card_number`, "
  "`age`, "
  "`email`, "
  "`address`, "
  "`phone`, "
  "`mobile`, "
  "`picture_address`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::find_statement[] =
  "SELECT "
  "`person`.`id`, "
  "`person`.`first_name`, "
  "`person`.`last_name`, "
  "`person`.`national_card_number`, "
  "`person`.`age`, "
  "`person`.`email`, "
  "`person`.`address`, "
  "`person`.`phone`, "
  "`person`.`mobile`, "
  "`person`.`picture_address` "
  "FROM `person` "
  "WHERE `person`.`id`=?";

  const char access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::update_statement[] =
  "UPDATE `person` "
  "SET "
  "`first_name`=?, "
  "`last_name`=?, "
  "`national_card_number`=?, "
  "`age`=?, "
  "`email`=?, "
  "`address`=?, "
  "`phone`=?, "
  "`mobile`=?, "
  "`picture_address`=? "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::erase_statement[] =
  "DELETE FROM `person` "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::query_statement[] =
  "SELECT "
  "`person`.`id`, "
  "`person`.`first_name`, "
  "`person`.`last_name`, "
  "`person`.`national_card_number`, "
  "`person`.`age`, "
  "`person`.`email`, "
  "`person`.`address`, "
  "`person`.`phone`, "
  "`person`.`mobile`, "
  "`person`.`picture_address` "
  "FROM `person`";

  const char access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::erase_query_statement[] =
  "DELETE FROM `person`";

  const char access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::table_name[] =
  "`person`";

  void access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.Id_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.Id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.Id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::pointer_type
  access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.Id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::object_type >
  access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::anar::parspark::model::PersonModel, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
