/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `person`;

CREATE TABLE `person`
(
    `id`                   BIGINT UNSIGNED  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `first_name`           VARCHAR(100)     NOT NULL CHECK (`first_name` != ''),
    `last_name`            VARCHAR(100)     NOT NULL CHECK (`last_name` != ''),
    `national_card_number` BIGINT UNSIGNED  NULL CHECK (`national_card_number` BETWEEN 1000000000 AND 9999999999),
    `age`                  TINYINT UNSIGNED NULL CHECK (`age` BETWEEN 1 AND 255),
    `email`                VARCHAR(100)     NOT NULL CHECK (`email` != ''),
    `address`              VARCHAR(500)     NULL CHECK (`address` != ''),
    `phone`                VARCHAR(12)      NULL CHECK (`phone` != ''),
    `mobile`               VARCHAR(12)      NULL CHECK (`mobile` != ''),
    `picture_address`      VARCHAR(1024)    NULL CHECK (`picture_address` != '')
)
    ENGINE = InnoDB;

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user`
(
    `id`           BIGINT UNSIGNED                       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `user_name`    VARCHAR(100)                          NOT NULL CHECK (LENGTH(`user_name`) > 6),
    `pass_word`    VARCHAR(1024)                         NOT NULL CHECK (LENGTH(`pass_word`) > 64),
    `person_id`    BIGINT UNSIGNED                       NULL,
    `type`         ENUM ('admin', 'manager', 'employee') NOT NULL DEFAULT 'employee',
    `created_time` TIMESTAMP(6)                          NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_time` TIMESTAMP(6)                          NULL,
    CHECK (`updated_time` > `created_time`)
)
    ENGINE = InnoDB;

CREATE UNIQUE INDEX `user_name_i`
    ON `user` (`user_name`);

ALTER TABLE `user`
    ADD CONSTRAINT `user_person_id_fk`
        FOREIGN KEY (`person_id`)
            REFERENCES `person` (`id`);

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `organization`;

CREATE TABLE `organization`
(
    `creating_user_id` BIGINT UNSIGNED NOT NULL,
    `updating_user_id` BIGINT UNSIGNED NULL,
    `created_time`     timestamp       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_time`     timestamp       NULL,
    CHECK (`updated_time` > `created_time`),
    `id`               BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name`             VARCHAR(500)    NOT NULL CHECK (`name` != ''),
    `abbreviation`     VARCHAR(50)     NOT NULL CHECK (`abbreviation` != ''),
    `picture_address`  VARCHAR(1024)   NULL CHECK (`picture_address` != '')
)
    ENGINE = InnoDB;

ALTER TABLE `organization`
    ADD CONSTRAINT `organization_creating_user_id_fk`
        FOREIGN KEY (`creating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `organization_updating_user_id_fk`
        FOREIGN KEY (`updating_user_id`)
            REFERENCES `user` (`id`);


/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `driver`;

CREATE TABLE `driver`
(
    `creating_user_id`       BIGINT UNSIGNED NOT NULL,
    `updating_user_id`       BIGINT UNSIGNED NULL,
    `created_time`           timestamp       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_time`           timestamp       NULL,
    CHECK (`updated_time` > `created_time`),
    `id`                     BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `driving_license_number` VARCHAR(100)    NULL CHECK (`driving_license_number` != ''),
    `person_id`              BIGINT UNSIGNED NOT NULL,
    `organization_id`        BIGINT UNSIGNED NULL,
    `picture_address`        VARCHAR(1024)   NULL CHECK (`picture_address` != '')
)
    ENGINE = InnoDB;

ALTER TABLE `driver`
    ADD CONSTRAINT `driver_creating_user_id_fk`
        FOREIGN KEY (`creating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `driver_updating_user_id_fk`
        FOREIGN KEY (`updating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `driver_person_id_fk`
        FOREIGN KEY (`person_id`)
            REFERENCES `person` (`id`),
    ADD CONSTRAINT `driver_organization_id_fk`
        FOREIGN KEY (`organization_id`)
            REFERENCES `organization` (`id`);

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `card`;

CREATE TABLE `card`
(
    `creating_user_id` BIGINT UNSIGNED NOT NULL,
    `updating_user_id` BIGINT UNSIGNED NULL,
    `created_time`     timestamp       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_time`     timestamp       NULL,
    CHECK (`updated_time` > `created_time`),
    `id`               BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `code`             VARCHAR(32)     NOT NULL CHECK (`code` != ''),
    `key`              VARCHAR(128)    NOT NULL CHECK (`key` != '')
)
    ENGINE = InnoDB;

ALTER TABLE `card`
    ADD CONSTRAINT `card_creating_user_id_fk`
        FOREIGN KEY (`creating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `card_updating_user_id_fk`
        FOREIGN KEY (`updating_user_id`)
            REFERENCES `user` (`id`);

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `car`;

CREATE TABLE `car`
(
    `creating_user_id` BIGINT UNSIGNED NOT NULL,
    `updating_user_id` BIGINT UNSIGNED NULL,
    `created_time`     timestamp       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_time`     timestamp       NULL,
    CHECK (`updated_time` > `created_time`),
    `id`               BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `plate_number_en`  VARCHAR(20)     NOT NULL CHECK (`plate_number_en` != ''),
    `driver_id`        BIGINT UNSIGNED NULL,
    `person_id`        BIGINT UNSIGNED NULL,
    `picture_address`  VARCHAR(1024)   NULL CHECK (`picture_address` != '')
)
    ENGINE = InnoDB;

ALTER TABLE `car`
    ADD CONSTRAINT `car_creating_user_id_fk`
        FOREIGN KEY (`creating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `car_updating_user_id_fk`
        FOREIGN KEY (`updating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `car_driver_id_fk`
        FOREIGN KEY (`driver_id`)
            REFERENCES `driver` (`id`),
    ADD CONSTRAINT `car_person_id_fk`
        FOREIGN KEY (`person_id`)
            REFERENCES `organization` (`id`);

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `black_list`;

CREATE TABLE `black_list`
(
    `creating_user_id` BIGINT UNSIGNED NOT NULL,
    `updating_user_id` BIGINT UNSIGNED NULL,
    `created_time`     timestamp       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_time`     timestamp       NULL,
    CHECK (`updated_time` > `created_time`),
    `id`               BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `plate_number_en`  VARCHAR(20)     NOT NULL CHECK (`plate_number_en` != ''),
    `description`      VARCHAR(4096)   NOT NULL CHECK (`description` != '')
)
    ENGINE = InnoDB;

ALTER TABLE `black_list`
    ADD CONSTRAINT `black_list_creating_user_id_fk`
        FOREIGN KEY (`creating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `black_list_updating_user_id_fk`
        FOREIGN KEY (`updating_user_id`)
            REFERENCES `user` (`id`);

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `lost_card`;

CREATE TABLE `lost_card`
(
    `creating_user_id` BIGINT UNSIGNED NOT NULL,
    `updating_user_id` BIGINT UNSIGNED NULL,
    `created_time`     timestamp       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_time`     timestamp       NULL,
    CHECK (`updated_time` > `created_time`),
    `id`               BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `card_id`          BIGINT UNSIGNED NOT NULL,
    `car_id`           BIGINT UNSIGNED NOT NULL,
    `penalty_cost`     INT UNSIGNED    NOT NULL CHECK (`penalty_cost` > 999),
    `description`      VARCHAR(4096)   NOT NULL CHECK (`description` != '')
)
    ENGINE = InnoDB;

ALTER TABLE `lost_card`
    ADD CONSTRAINT `lost_card_creating_user_id_fk`
        FOREIGN KEY (`creating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `lost_card_updating_user_id_fk`
        FOREIGN KEY (`updating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `lost_card_card_id_fk`
        FOREIGN KEY (`card_id`)
            REFERENCES `card` (`id`),
    ADD CONSTRAINT `lost_card_car_id_fk`
        FOREIGN KEY (`car_id`)
            REFERENCES `car` (`id`);

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `subscription`;

CREATE TABLE `subscription`
(
    `creating_user_id`    BIGINT UNSIGNED NOT NULL,
    `updating_user_id`    BIGINT UNSIGNED NULL,
    `created_time`        timestamp       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_time`        timestamp       NULL,
    CHECK (`updated_time` > `created_time`),
    `id`                  BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `card_id`             BIGINT UNSIGNED NOT NULL,
    `validate_times_json` TEXT            NOT NULL CHECK (`validate_times_json` != ''),
    `subscription_cost`   INT UNSIGNED    NOT NULL CHECK (`subscription_cost` > 999),
    `car_id`              BIGINT UNSIGNED NULL,
    `driver_id`           BIGINT UNSIGNED NULL,
    `organization_id`     BIGINT UNSIGNED NULL
)
    ENGINE = InnoDB;

ALTER TABLE `subscription`
    ADD CONSTRAINT `subscription_creating_user_id_fk`
        FOREIGN KEY (`creating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `subscription_updating_user_id_fk`
        FOREIGN KEY (`updating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `subscription_card_id_fk`
        FOREIGN KEY (`card_id`)
            REFERENCES `card` (`id`),
    ADD CONSTRAINT `subscription_car_id_fk`
        FOREIGN KEY (`car_id`)
            REFERENCES `car` (`id`),
    ADD CONSTRAINT `subscription_driver_id_fk`
        FOREIGN KEY (`driver_id`)
            REFERENCES `driver` (`id`),
    ADD CONSTRAINT `subscription_organization_id_fk`
        FOREIGN KEY (`organization_id`)
            REFERENCES `organization` (`id`);

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `parking_log`;

CREATE TABLE `parking_log`
(
    `creating_user_id`      BIGINT UNSIGNED NOT NULL,
    `updating_user_id`      BIGINT UNSIGNED NULL,
    `created_time`          timestamp       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_time`          timestamp       NULL,
    CHECK (`updated_time` > `created_time`),
    `id`                    BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `card_id`               BIGINT UNSIGNED NOT NULL,
    `enter_plate_number`    VARCHAR(50)     NULL CHECK (`enter_plate_number` != ''),
    `exit_plate_number`     VARCHAR(50)     NULL CHECK (`exit_plate_number` != ''),
    `entered_time`          timestamp       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `exited_time`           timestamp       NULL,
    CHECK (`exited_time` > `entered_time`),
    `parking_cost`          INT UNSIGNED    NULL,
    `enter_picture_address` VARCHAR(1024)   NULL CHECK (`enter_picture_address` != ''),
    `exit_picture_address`  VARCHAR(1024)   NULL CHECK (`exit_picture_address` != ''),
    `subscription_id`       BIGINT UNSIGNED NULL
)
    ENGINE = InnoDB;

ALTER TABLE `parking_log`
    ADD CONSTRAINT `parking_log_creating_user_id_fk`
        FOREIGN KEY (`creating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `parking_log_updating_user_id_fk`
        FOREIGN KEY (`updating_user_id`)
            REFERENCES `user` (`id`),
    ADD CONSTRAINT `parking_log_card_id_fk`
        FOREIGN KEY (`card_id`)
            REFERENCES `card` (`id`),
    ADD CONSTRAINT `parking_log_subscription_id_fk`
        FOREIGN KEY (`subscription_id`)
            REFERENCES `subscription` (`id`);
