/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `subscription`;

CREATE TABLE `subscription` (
  `creating_user_id` BIGINT UNSIGNED NOT NULL,
  `updating_user_id` BIGINT UNSIGNED NULL,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_time` timestamp NULL , 
CHECK(`updated_time` > `created_time`),
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `card_id` BIGINT UNSIGNED NOT NULL,
  `validate_times_json` TEXT NOT NULL CHECK(`validate_times_json` != ''),
  `subscription_cost` INT UNSIGNED NOT NULL CHECK(`subscription_cost` > 999),
  `car_id` BIGINT UNSIGNED NULL,
  `driver_id` BIGINT UNSIGNED NULL,
  `organization_id` BIGINT UNSIGNED NULL)
 ENGINE=InnoDB;


ALTER TABLE `subscription`
  ADD CONSTRAINT `subscription_creating_user_id_fk`
    FOREIGN KEY (`creating_user_id`)
    REFERENCES `user` (`id`),
  ADD CONSTRAINT `subscription_updating_user_id_fk`
    FOREIGN KEY (`updating_user_id`)
    REFERENCES `user` (`id`),
  ADD CONSTRAINT `subscription_card_id_fk`
    FOREIGN KEY (`card_id`)
    REFERENCES `card` (`id`),
  ADD CONSTRAINT `subscription_car_id_fk`
    FOREIGN KEY (`car_id`)
    REFERENCES `car` (`id`),
  ADD CONSTRAINT `subscription_driver_id_fk`
    FOREIGN KEY (`driver_id`)
    REFERENCES `driver` (`id`),
  ADD CONSTRAINT `subscription_organization_id_fk`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organization` (`id`)


